### ISSUE TITLE
Relative survival models with external data

### ISSUE THREAD

**Issue by irtimmins** [chjackson/survextrap#13]
Hi Chris, Just trying to understand how to use the relative survival model with external data for the situation where we supply a quoted variable name with the background hazard at event times (rather than when we do it by supplying the hazard and time data frame).

In this case, when we want to include external data, it requires us to have `"backsurv_start"` and `"backsurv_stop"` columns in the external data. 

For this external data frame, if it's in yearly aggregate count data -  say a row had `start = 5`, `stop = 6`, `n = 400`, `r = 350` - would  `"backsurv_start"` and `"backsurv_stop"` be the expected background probability of surviving 5 and 6 years for the patients in the external data? So a row might have e.g. `backsurv_start = 0.92` and `backsurv_stop = 0.88` or something like that depending on the population?

If that's right, would you envisage getting these survival probabilities in practise by using something like `survexp` using a lifetable relevant to the external data? If the aggregate count data was for a sample with different ages/sex, would you provide the `"backsurv_start"` and `"backsurv_stop"` as some kind of standardised survival rates from a lifetable, say? 

For the trial data we supply background hazard rates at event times, and for the external data we supply background survival probabilities - are there references/equations for how this is implemented in survextrap?

**Comment by chjackson** [comment]
Yes - it is the probability of surviving up to `backsurv_start` and `backsurv_stop` respectively for a person alive at time 0.   I don't know where these might come from in practice.   

The model for relative survival with trial data is from [Nelson et al](https://doi.org/10.1002/sim.3064).   With the external data, the conditional probability of survival over each interval (for the binomial likelihood) is $S(t_{stop} | \theta) / S(t_{start} | \theta)$, where $S(t_{stop}|\theta) = R(t_{stop}| \theta) S_0(t_{stop})$  (and similarly for $t_{start}$), where $S_0()$ is the background survival function and $R$ is the relative survival.  So $\theta$ become the parameters describing the excess hazard function on top of the background, rather than the absolute hazard.  

Note this version of the model can't be used for extrapolation - that would need the background hazard to be supplied as a data frame covering all times.

**Comment by irtimmins** [comment]
Many thanks for providing the derivation, that makes sense :+1:
